export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const SET_VISITED_USER_INFO = 'SET_VISITED_USER_INFO';
export const TOGGLE_USER_SUBS = 'TOGGLE_USER_SUBS';
export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD';
export const LOGIN_USER = 'LOGIN_USER';
