export const TOGGLE_LIKE_POST = 'TOGGLE_LIKE_POST';
export const TOGGLE_LIKE_POST_LOADING = 'TOGGLE_LIKE_POST_LOADING';
export const TOGGLE_COMMENT_POST_LOADING = 'TOGGLE_COMMENT_LOADING';
export const WRITE_NEW_COMMENT = 'WRITE_NEW_COMMENT';
export const SET_USER_POSTS = 'SET_USER_POSTS';
export const ADD_USER_POST = 'ADD_USER_POST';
