export const TOGGLE_SUBS = 'TOGGLE_SUBS';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';
export const SET_RECOMMENDED_PROFILES = 'SET_RECOMMENDED_PROFILES';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
